version: 2.1
executors:
  my-executor:
    docker:
      - image: amazon/aws-cli

jobs:
  create_infra:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy \
                --stack-name my-stack \
                --template-file template.yml \
          
workflows:
  workflow-1:
    jobs:
      - create_infra