version: 2.1
executors:
  my-executor:
    docker:
      - image: amazon/aws-cli

jobs:
  create_infrastructure:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation create-stack \
              --stack-name my-app \
              --template-body file://template.yml \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region=us-east-1
          
workflows:
  workflow-1:
    jobs:
      - create_infrastructure