version: 2.1
executors:
  my-executor:
    docker:
      - image: amazon/aws-cli

jobs:
  create_network:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy \
                --stack-name network-ex \
                --template-file file://../../projects/project-2/network.yml \
                --parameter-overrides file://../../projects/project-2/network-parameters 
  create_servers:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy \
                --stack-name servers-ex \
                --template-file file://../../projects/project-2/LB-and-servers.yml \
                --parameter-overrides file://../../projects/project-2/servers-parameters
          
workflows:
  workflow-1:
    jobs:
      - create_network
      - create_servers:
          requires:
            - create_network