version: 2.1
executors:
  my-executor:
    docker:
      - image: amazon/aws-cli

jobs:
  create_network:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy \
                --stack-name network-ex \
                --template-file network.yml \
                --parameter-overrides file://network-parameters.json
  create_servers:
    executor: my-executor
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy \
                --stack-name servers-ex \
                --template-file file://LB-and-servers.yml \
                --parameter-overrides file://servers-parameters.json
          
workflows:
  workflow-1:
    jobs:
      - create_network
      - create_servers:
          requires:
            - create_network